(el-get 'sync 'org-site)
(add-to-list 'load-path "~/.emacs.d/el-get/org-site")
(add-to-list 'load-path "~/.emacs.d/el-get/with-namespace")
(add-to-list 'load-path "~/.emacs.d/el-get/s")
(add-to-list 'load-path "~/.emacs.d/el-get/ht")
(add-to-list 'load-path "~/.emacs.d/el-get/dash")
(add-to-list 'load-path "~/.emacs.d/el-get/mustache")
(add-to-list 'load-path "~/.emacs.d/el-get/loop")
(require 'org-site)
(provide 'init-org-site)
